[workspace]

members = [
  "luminance",
  "luminance-derive",
  "luminance-examples",
  "luminance-gl",
  "luminance-glfw",
  "luminance-glutin",
  "luminance-sdl2",
  "luminance-webgl",
  "luminance-windowing",
]

[patch.crates-io]
luminance = { path = "./luminance" }
luminance-derive = { path = "./luminance-derive" }
luminance-examples = { path = "./luminance-examples" }
luminance-gl = { path = "./luminance-gl" }
luminance-glfw = { path = "./luminance-glfw" }
luminance-glutin = { path = "./luminance-glutin" }
luminance-sdl2 = { path = "./luminance-sdl2" }
luminance-windowing = { path = "./luminance-windowing" }
