[package]
name = "viewer"
version = "0.1.1"
license = "BSD-3-Clause"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]
description = "A 3D viewer"
keywords = ["3D", "viewer"]
homepage = "https://github.com/phaazon/luminance-rs"
repository = "https://github.com/phaazon/luminance-rs"
readme = "README.md"
edition = "2018"

[dependencies]
cgmath = "0.17"
luminance = "0.39"
luminance-derive = "0.5"
luminance-glfw = "0.12"
try-guard = "0.2"
wavefront_obj = "7"
