name: CI
on: [pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxrandr-dev xorg-dev libsdl2-dev
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose

  build-macosx:
    runs-on: macOS-latest
    steps:
      - name: Install dependencies
        run: brew install SDL2
      - uses: actions/checkout@v1
      - name: Install Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile=minimal
      - name: Build
        run: |
          . ~/.cargo/env
          cargo build --verbose
      - name: Test
        run: |
          . ~/.cargo/env
          cargo test --verbose

  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          cargo install --force cargo-sync-readme
          rustup component add rustfmt
      - name: cargo sync-readme
        run: |
          cd $GITHUB_WORKSPACE/luminance
          cargo sync-readme -c
          cd $GITHUB_WORKSPACE/luminance-derive
          cargo sync-readme -c
          cd $GITHUB_WORKSPACE/luminance-gl
          cargo sync-readme -c
          cd $GITHUB_WORKSPACE/luminance-glfw
          cargo sync-readme -c
          cd $GITHUB_WORKSPACE/luminance-glutin
          cargo sync-readme -c
          cd $GITHUB_WORKSPACE/luminance-sdl2
          cargo sync-readme -c
          cd $GITHUB_WORKSPACE/luminance-webgl
          cargo sync-readme -c
          cd $GITHUB_WORKSPACE/luminance-windowing
          cargo sync-readme -c
      - name: rustfmt
        run: cargo fmt -- --check
